- name: config nodejs
  hosts: backend
  become: yes
  tasks:
  - name: disbale node js
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs.20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node js
    ansible.builtin.command: dnf install nodejs -y